[dev]
  command = "yarn dev"
  # autoLaunch = false
  functions = "functions"
  framework = "#custom"
  port = 8888
  targetPort = 3000

[build]
  command = "yarn generate"
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "/api/analyze"
  to = "/.netlify/functions/analyze"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 200
  force = false
