[dev]
  command = "yarn dev"
  autoLaunch = false

[build]
  command = "yarn generate"
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "/api/analyze"
  to = "/.netlify/functions/analyze"
  status = 200
  force = true
