[dev]
  command = "yarn dev"
  # autoLaunch = false
  functions = "functions"
  framework = "#custom" 
  targetPort=8000

[build]
  command = "yarn generate"
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "/api/analyze"
  to = "/.netlify/functions/analyze"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Basic-Auth = "nuxt-admin:vue-telemetry-protected-area"
